name: Node.js CI

on:
  push:
    branches: [ "primary" ]
  pull_request:
    branches: [ "primary" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Find and list symlinks
        run: find . -type l -exec ls -l {} \;
      - name: Upload dist folder contents
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist/**/*
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist folder contents
        uses: actions/download-artifact@v4
        with:
          name: github-pages
      - name: List files for debug
        run: ls -lR
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
