name: Node.js CI

on:
  push:
    branches: [ "primary" ]
  pull_request:
    branches: [ "primary" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Upload build artifacts for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
          # 'path' should point to the directory with the files you want to deploy.

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
    environment:
      name: github-pages
